name: Build, Analyze, Monitor with sonar cube 


on:
  push:
    branches:
      - master

jobs:
  build-and-analyze:
    name: Build, SonarQube Analysis, 
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures that SonarQube analysis has full commit history

      # SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      